sudo: required
services:
  - docker

before_install:
  docker build -t hbgjr/frontend .

script:
  docker run hbgjr/frontend ls

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Dockertest
  env: Dockertest-env
  bucket_name: elasticbeanstalk-us-east-2-480461736399
  bucket_path: Dockertest
  on:
    branch: master
  acess_key_id: $AWS_ACCESS_KEY
  secret_acess_key:
    secure: "$AWS_SECRET_KEY"